## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cpu


In [3]:
print("Hello I'am excited to start the PyTorch course")

Hello I'am excited to start the PyTorch course


## Introduction to Tensors

#### create tensors

In [4]:
## scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [5]:
scalar.ndim

0

In [6]:
## Get tensor back as python int
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([9, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor 
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
tensor.ndim 

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

### Random tensors

Why are random tensors important?

Training starts with random weights. We compute the loss, run backpropagation, and update the weights in the direction that reduces the loss. We repeat these steps many times (often thousands) until the model is close to the correct solution.

Super-short version:
Start with random numbers → compute loss → backpropagate → update weights → repeat many times.

In [17]:
# create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0763, 0.3872, 0.1854, 0.0777],
        [0.0094, 0.4050, 0.9095, 0.0683],
        [0.9015, 0.2684, 0.0020, 0.2659]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor.shape

torch.Size([3, 4])

In [20]:
## create a random tensor with similar shape to an image tensor.
random_tenso_image = torch.rand(size=(3,224,224))# 
random_tenso_image

tensor([[[0.1874, 0.2263, 0.6517,  ..., 0.9641, 0.9571, 0.4873],
         [0.9756, 0.4761, 0.7944,  ..., 0.2043, 0.6581, 0.8955],
         [0.6750, 0.2303, 0.1171,  ..., 0.6221, 0.8172, 0.2626],
         ...,
         [0.7950, 0.0201, 0.4413,  ..., 0.9738, 0.6208, 0.8156],
         [0.0495, 0.0761, 0.6986,  ..., 0.2558, 0.7966, 0.9868],
         [0.1778, 0.3418, 0.8275,  ..., 0.7602, 0.5291, 0.2418]],

        [[0.4141, 0.1943, 0.3365,  ..., 0.0612, 0.5134, 0.8669],
         [0.0356, 0.5056, 0.2549,  ..., 0.5206, 0.9765, 0.8387],
         [0.6349, 0.1074, 0.6165,  ..., 0.3620, 0.7175, 0.3771],
         ...,
         [0.9006, 0.1239, 0.8974,  ..., 0.9139, 0.6834, 0.1495],
         [0.8550, 0.4860, 0.3646,  ..., 0.0966, 0.8001, 0.5213],
         [0.3642, 0.4218, 0.2217,  ..., 0.4837, 0.2158, 0.5980]],

        [[0.8916, 0.4101, 0.3233,  ..., 0.0910, 0.3746, 0.5445],
         [0.7938, 0.0555, 0.6574,  ..., 0.1430, 0.5641, 0.4655],
         [0.5614, 0.6162, 0.0252,  ..., 0.0508, 0.7895, 0.

In [21]:
random_tenso_image.shape

torch.Size([3, 224, 224])

In [22]:
random_tenso_image.ndim

3

## Zeros and ones

In [23]:
# create tensors of zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# create tensors of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones.dtype

torch.float32

## Creating a range of tensors and tesors-like

In [27]:
# use torch.range() and get deprecated message, use torch.arange()

one_to_ten = torch.range(start=1, end=50, step=7)
one_to_ten

C:\Users\gubra\AppData\Local\Temp\ipykernel_28644\2586928959.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start=1, end=50, step=7)


tensor([ 1.,  8., 15., 22., 29., 36., 43., 50.])

In [28]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0.])

## tensor datatypes

Note: Tensor datatypes is one of the 3 big errors you will run into with PyTorch and deeep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


For every sensor we have to know the datatype, shape, device sa we can avoid the errors.

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0 , 9.0],
                               dtype=None, # what datatype is the tensor (float 32)
                               device=None,
                               requires_grad=False)

float_32_tensor.dtype

torch.float32

In [30]:
## try to change the type of a sensor
float_32_tensor = float_32_tensor.type(torch.float16)
float_32_tensor.dtype

torch.float16

In [31]:
int_32_tesnor = torch.tensor([3, 5, 10], dtype =torch.int32) 
int_32_tesnor

tensor([ 3,  5, 10], dtype=torch.int32)

In [32]:
int_32_tesnor * float_32_tensor

tensor([ 9., 30., 90.], dtype=torch.float16)

In [37]:
## create a tensor
tensor_ex = torch.rand([3,224,224])
tensor_ex

tensor([[[0.7431, 0.4028, 0.8196,  ..., 0.0793, 0.5954, 0.6591],
         [0.8386, 0.9375, 0.5566,  ..., 0.7453, 0.2358, 0.4454],
         [0.2228, 0.4933, 0.6192,  ..., 0.3710, 0.6015, 0.6894],
         ...,
         [0.7305, 0.4997, 0.5787,  ..., 0.4902, 0.1786, 0.2093],
         [0.7564, 0.1953, 0.5924,  ..., 0.0785, 0.2073, 0.7499],
         [0.5173, 0.7977, 0.7124,  ..., 0.2311, 0.7475, 0.8893]],

        [[0.9524, 0.1354, 0.3939,  ..., 0.7231, 0.5552, 0.0645],
         [0.3978, 0.1224, 0.1512,  ..., 0.0974, 0.7303, 0.7776],
         [0.5257, 0.8464, 0.7497,  ..., 0.2444, 0.3856, 0.8051],
         ...,
         [0.9801, 0.3564, 0.9376,  ..., 0.3306, 0.5362, 0.9854],
         [0.5101, 0.6589, 0.7515,  ..., 0.6302, 0.9867, 0.2160],
         [0.8235, 0.6167, 0.0579,  ..., 0.5771, 0.9948, 0.7863]],

        [[0.2386, 0.4730, 0.6102,  ..., 0.5438, 0.8574, 0.1082],
         [0.9921, 0.3926, 0.5972,  ..., 0.6415, 0.0597, 0.1841],
         [0.2421, 0.8895, 0.1567,  ..., 0.5057, 0.6769, 0.

In [38]:
## finds out the details for the tensor
# device, shape, dttype

print("This is the divice of the sensor", tensor_ex.device)
print("This is the shape of the sensor", tensor_ex.shape)
print("This is the dtype of the sensor", tensor_ex.dtype)

This is the divice of the sensor cpu
This is the shape of the sensor torch.Size([3, 224, 224])
This is the dtype of the sensor torch.float32
