## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cpu


In [3]:
print("Hello I'am excited to start the PyTorch course")

Hello I'am excited to start the PyTorch course


## Introduction to Tensors

#### create tensors

In [4]:
## scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [5]:
scalar.ndim

0

In [6]:
## Get tensor back as python int
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([9, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor 
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
tensor.ndim 

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])